import { GridRow } from '../../../../../../shared/Globals/types/filterBlock';

export const gridCols: GridRow[] = [
  // { field: 'user_id', size: '220px', is_sortable_flag: true },
  { field: 'org_name', size: '220px', is_sortable_flag: true },
  { field: 'first_last_name', size: '220px', is_sortable_flag: true },
  { field: 'login', size: '140px', is_sortable_flag: true },
  { field: 'start_date', size: '100px', is_sortable_flag: true },
  { field: 'end_date', size: '200px', is_sortable_flag: true },
  { field: 'is_active_flag_name', size: '70px', is_sortable_flag: true },
];

export const filterBlock = [
  {
    fieldName: 'org_name',
    name: 'e.organizationId',
    displayOrder: 2,
    filterCondition: '=',
    filterDisplayTypeCode: 'FB',
    filterDictCode: 'TEST',
    filterCodeProperty: '-1',
    width: '220',
    isSortableFlagCode: 'Y',
    dataTypeId: 2,

    applicationCode: 'CORE',
    colTypeCode: 'STANDARD',
    sortColName: 'a.name1',
    filterColName: 'a.applicationCode',
    // filterUpperSign: null,
    // filterLikePercSign: null,
    filterGroup: null,
    filterAttributeCode: null,
    filterNameProperty: 'name',
    filterDictFormClassRefName: null,
  },
  {
    fieldName: 'user_id',
    name: 'user_id',
    displayOrder: 2,
    filterCondition: 'BETWEEN',
    filterDisplayTypeCode: 'F',
    filterDictCode: 'TEST',
    filterCodeProperty: '-1',
    width: '220',
    isSortableFlagCode: 'Y',
    dataTypeId: 2,

    applicationCode: 'CORE',
    colTypeCode: 'STANDARD',
    sortColName: 'a.name1',
    filterColName: 'user_id',
    filterGroup: null,
    filterAttributeCode: null,
    filterNameProperty: 'name',
    filterDictFormClassRefName: null,
  },

  {
    fieldName: 'first_last_name',
    name: 'e.firstLastName',
    displayOrder: 1,
    filterCondition: 'LIKE',
    filterDisplayTypeCode: 'F',
    filterDictCode: 'TEST',
    filterCodeProperty: '-1',
    filterUpperSign: 'BOTH',
    filterLikePercSign: 'ALL',
    width: '220',
    isSortableFlagCode: 'Y',

    applicationCode: 'CORE',
    dataTypeId: 1,
    colTypeCode: 'STANDARD',
    sortColName: 'a.name1',
    filterColName: 'e.firstLastName',
    filterGroup: null,
    filterAttributeCode: null,
    filterNameProperty: 'name',
    filterDictFormClassRefName: null,
  },

  {
    fieldName: 'login',
    name: 'e.login',
    displayOrder: 1,
    filterCondition: 'LIKE',
    filterDisplayTypeCode: 'F',
    filterDictCode: 'TEST',
    filterCodeProperty: '-1',
    filterUpperSign: 'BOTH',
    filterLikePercSign: 'ALL',
    width: '140',
    isSortableFlagCode: 'Y',

    applicationCode: 'CORE',
    dataTypeId: 1,
    colTypeCode: 'STANDARD',
    sortColName: 'a.name1',
    filterColName: 'e.login',
    filterGroup: null,
    filterAttributeCode: null,
    filterNameProperty: 'name',
    filterDictFormClassRefName: null,
  },
  {
    fieldName: 'is_active_flag_name',
    name: 'e.isActiveFlagCode',
    displayOrder: 1,
    filterCondition: '=',
    filterDisplayTypeCode: 'L',
    filterDictCode: 'TEST',
    filterCodeProperty: '-1',
    filterUpperSign: 'BOTH',
    filterLikePercSign: 'ALL',
    filterAttributeCode: 'YES_NO',
    width: '70',
    isSortableFlagCode: 'Y',

    applicationCode: 'CORE',
    dataTypeId: 1,
    colTypeCode: 'STANDARD',
    sortColName: 'a.name1',
    filterColName: 'e.isActiveFlagCode',
    filterGroup: null,
    filterNameProperty: 'name',
    filterDictFormClassRefName: null,
  },
];

export const filterBlock2 = [
  {
    itemName: 'org_name',
    colName: 'e.organizationId',
    dataType: 2,
    condition: '=',
    value: '',
    displayType: 'FB',
    dictCode: 'TEST',
    codeProperty: '-1',
  },
  {
    itemName: 'user_id',
    colName: 'user_id',
    dataType: 2,
    condition: 'BETWEEN',
    value: '',
    displayType: 'F',
  },
  {
    itemName: 'first_last_name',
    colName: 'e.firstLastName',
    dataType: 1,
    condition: 'LIKE',
    upperSign: 'BOTH',
    likePercSign: 'ALL',
    value: '',
    displayType: 'F',
  },
  {
    itemName: 'login',
    colName: 'e.login',
    dataType: 1,
    condition: 'LIKE',
    upperSign: 'BOTH',
    likePercSign: 'ALL',
    value: '',
    displayType: 'F',
  },
  {
    itemName: 'is_active_flag_name',
    colName: 'e.isActiveFlagCode',
    condition: '=',
    dataType: 1,
    displayType: 'L',
    dictCode: 'TEST',
    codeProperty: 'code',
    nameProperty: 'name',
    attrCode: 'YES_NO',
  },
];

//     organizationId: 43,
//     organizationCode: 'main_seven',
//     name: 'Головная организация 7',
//     iconCode: null,
//     childCount: 2,
//     parentOrganizationId: null,

export const standartInputs = [
  {
    itemName: 'first',
    colName: 'e.first',
    dataType: 1,
    displayType: 'F',
    value: '',
    required: true,
  },
  {
    itemName: 'two',
    colName: 'e.two',
    dataType: 1,
    displayType: 'F',
    value: '',
    required: true,
  },
  {
    itemName: 'tree',
    colName: 'e.tree',
    dataType: 1,
    displayType: 'F',
    value: '',
    required: false,
  },
];
