export const inputsData = [
  {
    token: 'roleCode',
    applicationCode: 'CORE',
    name: 'Код роли',
    isNullableFlag: 'N',
    isEditableFlag: 'Y',
    orderNumber: 1,
    maxlength: 64,
    height: null,
    width: null,
    colStyle: null,
    codeProperty: null,
    nameProperty: null,
    defaultValueTypeCode: null,
    defaultValue: null,
    isForOutputFlag: 'Y',
    subgroupCode: null,
    attributeCode: 'F_STR',
    parentAttributeCode: null,
    parentReloadDsFlag: null,
    dataTypeId: 1,
    displayTypeCode: 'F',
    dictCode: null,
    dictFormClassRefName: null,
    defValData: null,
  },
  {
    token: 'applicationCode',
    applicationCode: 'CORE',
    name: 'Приложение',
    isNullableFlag: 'N',
    isEditableFlag: 'Y',
    orderNumber: 2,
    maxlength: null,
    height: null,
    width: null,
    colStyle: null,
    codeProperty: 'code',
    nameProperty: 'name',
    defaultValueTypeCode: null,
    defaultValue: null,
    isForOutputFlag: 'Y',
    subgroupCode: null,
    attributeCode: 'CORE_APPLICATIONS',
    parentAttributeCode: null,
    parentReloadDsFlag: null,
    dataTypeId: 1,
    displayTypeCode: 'L',
    dictCode: null,
    dictFormClassRefName: null,
    defValData: null,
  },
  {
    token: 'name1',
    applicationCode: 'CORE',
    name: 'Наименование на русском языке',
    isNullableFlag: 'N',
    isEditableFlag: 'Y',
    orderNumber: 3,
    maxlength: 128,
    height: null,
    width: null,
    colStyle: null,
    codeProperty: null,
    nameProperty: null,
    defaultValueTypeCode: null,
    defaultValue: null,
    isForOutputFlag: 'Y',
    subgroupCode: null,
    attributeCode: 'F_STR',
    parentAttributeCode: null,
    parentReloadDsFlag: null,
    dataTypeId: 1,
    displayTypeCode: 'F',
    dictCode: null,
    dictFormClassRefName: null,
    defValData: null,
  },
  {
    token: 'name2',
    applicationCode: 'CORE',
    name: 'На узбекском',
    isNullableFlag: 'N',
    isEditableFlag: 'Y',
    orderNumber: 4,
    maxlength: 128,
    height: null,
    width: null,
    colStyle: null,
    codeProperty: null,
    nameProperty: null,
    defaultValueTypeCode: null,
    defaultValue: null,
    isForOutputFlag: 'Y',
    subgroupCode: null,
    attributeCode: 'F_STR',
    parentAttributeCode: null,
    parentReloadDsFlag: null,
    dataTypeId: 1,
    displayTypeCode: 'F',
    dictCode: null,
    dictFormClassRefName: null,
    defValData: null,
    widthItem: '100px',
  },
  {
    token: 'name3',
    applicationCode: 'CORE',
    name: 'На английском',
    isNullableFlag: 'N',
    isEditableFlag: 'Y',
    orderNumber: 5,
    maxlength: 128,
    height: null,
    width: null,
    colStyle: null,
    codeProperty: null,
    nameProperty: null,
    defaultValueTypeCode: null,
    defaultValue: null,
    isForOutputFlag: 'Y',
    subgroupCode: null,
    attributeCode: 'F_STR',
    parentAttributeCode: null,
    parentReloadDsFlag: null,
    dataTypeId: 1,
    displayTypeCode: 'F',
    dictCode: null,
    dictFormClassRefName: null,
    defValData: null,
    widthItem: '100px',
  },
];

export const attrDataNoBD = {
  CORE_APPLICATIONS: [
    {
      code: 'OS',
      name: 'Организационная структура',
    },
    {
      code: 'CORE',
      name: 'Базовый функционал',
    },
  ],
};

// ---------------------------------------

export const fildListAddNew = [
  {
    token: 'firstLastName',
    name: 'Фамилия, Имя, Отчество',
    displayTypeCode: 'F',
    attribute_code: 'FIO',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 256,
  },
  {
    token: 'login',
    name: 'Логин',
    displayTypeCode: 'F',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 256,
  },
  {
    token: 'password',
    name: 'Пароль',
    displayTypeCode: 'F',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 16,
    col_style: 'col-6',
    is_password: true,
  },
  {
    token: 'changePasswordFlagCode',
    name: 'Сменить пароль?',
    displayTypeCode: 'CH',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
  },
  {
    token: 'addInfo',
    name: 'Описание',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 1024,
  },
  {
    token: 'emailAddress',
    name: 'E-Mail',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 128,
  },
  {
    token: 'address',
    name: 'Адрес',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 256,
  },
  {
    token: 'telefon',
    name: 'Телефон',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 80,
    col_style: 'col-6',
  },
  {
    token: 'fax',
    name: 'Факс',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 80,
    col_style: 'col-6',
  },
  {
    token: 'startDate',
    name: 'Срок действия (с даты)',
    attribute_code: 'FIO',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 4,
    col_style: 'col-6',
    default_value_type: 'CONST',
    // default_value: formatDate(new Date(), 'dd.MM.yyyy', 'en'),
  },
  {
    token: 'endDate',
    name: 'Срок действия (по дату)',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 4,
    col_style: 'col-6',
  },
  {
    token: 'employeeId',
    name: 'Сотрудник',
    attribute_code: 'FIO',
    displayTypeCode: 'DQ',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 2,
    dict_code: 'OS_EMPLOYEES',
    dict_code_property: 'employee_id',
    dict_name_property: 'full_name',
  },
  {
    token: 'organizationId',
    name: 'Организация по умолчанию',
    attribute_code: 'FIO',
    displayTypeCode: 'FB',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 2,
    dict_form_class_ref_name: 'getOrg',
    dict_code_property: 'key',
    dict_name_property: 'label',
  },
  {
    token: 'isActiveFlagCode',
    name: 'Активен?',
    displayTypeCode: 'CH',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    default_value_type: 'CONST',
    default_value: 'N',
  },
];

export const fildListAddNewEdit = [
  {
    token: 'firstLastName',
    name: 'Фамилия, Имя, Отчество',
    displayTypeCode: 'F',
    attribute_code: 'FIO',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 256,
    // value: 'Иванов Иван Иванович',
  },
  {
    token: 'login',
    name: 'Логин',
    displayTypeCode: 'F',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 256,
  },
  {
    token: 'password',
    name: 'Пароль',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 16,
    col_style: 'col-6',
    is_password: true,
  },
  {
    token: 'changePasswordFlagCode',
    name: 'Сменить пароль?',
    displayTypeCode: 'CH',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
  },
  {
    token: 'addInfo',
    name: 'Описание',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 1024,
  },
  {
    token: 'emailAddress',
    name: 'E-Mail',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 128,
  },
  {
    token: 'address',
    name: 'Адрес',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 256,
  },
  {
    token: 'telefon',
    name: 'Телефон',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 80,
    col_style: 'col-6',
  },
  {
    token: 'fax',
    name: 'Факс',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 80,
    col_style: 'col-6',
  },
  {
    token: 'startDate',
    name: 'Срок действия (с даты)',
    attribute_code: 'FIO',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 4,
    col_style: 'col-6',
    default_value_type: 'CONST',
    // default_value: formatDate(new Date(), 'dd.MM.yyyy', 'en'),
  },
  {
    token: 'endDate',
    name: 'Срок действия (по дату)',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 4,
    col_style: 'col-6',
  },
  {
    token: 'employeeId',
    name: 'Сотрудник',
    attribute_code: 'FIO',
    displayTypeCode: 'DQ',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 2,
    dict_code: 'OS_EMPLOYEES',
    dict_code_property: 'employee_id',
    dict_name_property: 'full_name',
  },
  {
    token: 'organizationId',
    name: 'Организация по умолчанию',
    attribute_code: 'FIO',
    displayTypeCode: 'FB',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 2,
    dict_form_class_ref_name: 'getOrg',
    dict_code_property: 'key',
    dict_name_property: 'label',
  },
  {
    token: 'isActiveFlagCode',
    name: 'Активен?',
    displayTypeCode: 'CH',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    default_value_type: 'CONST',
    default_value: 'N',
  },
];
