export const inputsData = [
  {
    token: 'roleCode',
    applicationCode: 'CORE',
    name: 'Код роли',
    isNullableFlag: 'N',
    isEditableFlag: 'Y',
    orderNumber: 1,
    maxlength: 64,
    height: null,
    width: null,
    colStyle: null,
    codeProperty: null,
    nameProperty: null,
    defaultValueTypeCode: null,
    defaultValue: null,
    isForOutputFlag: 'Y',
    subgroupCode: null,
    attributeCode: 'F_STR',
    parentAttributeCode: null,
    parentReloadDsFlag: null,
    dataTypeId: 1,
    displayTypeCode: 'F',
    dictCode: null,
    dictFormClassRefName: null,
    defValData: null,
  },
  {
    token: 'applicationCode',
    applicationCode: 'CORE',
    name: 'Приложение',
    isNullableFlag: 'N',
    isEditableFlag: 'Y',
    orderNumber: 2,
    maxlength: null,
    height: null,
    width: null,
    colStyle: null,
    codeProperty: 'code',
    nameProperty: 'name',
    defaultValueTypeCode: null,
    defaultValue: null,
    isForOutputFlag: 'Y',
    subgroupCode: null,
    attributeCode: 'CORE_APPLICATIONS',
    parentAttributeCode: null,
    parentReloadDsFlag: null,
    dataTypeId: 1,
    displayTypeCode: 'L',
    dictCode: null,
    dictFormClassRefName: null,
    defValData: null,
  },
  {
    token: 'name1',
    applicationCode: 'CORE',
    name: 'Наименование на русском языке',
    isNullableFlag: 'N',
    isEditableFlag: 'Y',
    orderNumber: 3,
    maxlength: 128,
    height: null,
    width: null,
    colStyle: null,
    codeProperty: null,
    nameProperty: null,
    defaultValueTypeCode: null,
    defaultValue: null,
    isForOutputFlag: 'Y',
    subgroupCode: null,
    attributeCode: 'F_STR',
    parentAttributeCode: null,
    parentReloadDsFlag: null,
    dataTypeId: 1,
    displayTypeCode: 'F',
    dictCode: null,
    dictFormClassRefName: null,
    defValData: null,
  },
  {
    token: 'name2',
    applicationCode: 'CORE',
    name: 'На узбекском',
    isNullableFlag: 'N',
    isEditableFlag: 'Y',
    orderNumber: 4,
    maxlength: 128,
    height: null,
    width: null,
    colStyle: null,
    codeProperty: null,
    nameProperty: null,
    defaultValueTypeCode: null,
    defaultValue: null,
    isForOutputFlag: 'Y',
    subgroupCode: null,
    attributeCode: 'F_STR',
    parentAttributeCode: null,
    parentReloadDsFlag: null,
    dataTypeId: 1,
    displayTypeCode: 'F',
    dictCode: null,
    dictFormClassRefName: null,
    defValData: null,
    widthItem: '100px',
  },
  {
    token: 'name3',
    applicationCode: 'CORE',
    name: 'На английском',
    isNullableFlag: 'N',
    isEditableFlag: 'Y',
    orderNumber: 5,
    maxlength: 128,
    height: null,
    width: null,
    colStyle: null,
    codeProperty: null,
    nameProperty: null,
    defaultValueTypeCode: null,
    defaultValue: null,
    isForOutputFlag: 'Y',
    subgroupCode: null,
    attributeCode: 'F_STR',
    parentAttributeCode: null,
    parentReloadDsFlag: null,
    dataTypeId: 1,
    displayTypeCode: 'F',
    dictCode: null,
    dictFormClassRefName: null,
    defValData: null,
    widthItem: '100px',
  },
];

export const attrDataNoBD = {
  CORE_APPLICATIONS: [
    {
      code: 'OS',
      name: 'Организационная структура',
    },
    {
      code: 'CORE',
      name: 'Базовый функционал',
    },
  ],
};

// ---------------------------------------

export const fildListAddNew = [
  {
    token: 'firstLastName',
    name: 'Фамилия, Имя, Отчество',
    displayTypeCode: 'F',
    attribute_code: 'FIO',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 256,
  },
  {
    token: 'login',
    name: 'Логин',
    displayTypeCode: 'F',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 256,
  },
  {
    token: 'password',
    name: 'Пароль',
    displayTypeCode: 'F',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 16,
    col_style: 'col-6',
    is_password: true,
  },
  {
    token: 'changePasswordFlagCode',
    name: 'Сменить пароль?',
    displayTypeCode: 'CH',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
  },
  {
    token: 'addInfo',
    name: 'Описание',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 1024,
  },
  {
    token: 'emailAddress',
    name: 'E-Mail',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 128,
  },
  {
    token: 'address',
    name: 'Адрес',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 256,
  },
  {
    token: 'telefon',
    name: 'Телефон',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 80,
    col_style: 'col-6',
  },
  {
    token: 'fax',
    name: 'Факс',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 80,
    col_style: 'col-6',
  },
  {
    token: 'startDate',
    name: 'Срок действия (с даты)',
    attribute_code: 'FIO',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 4,
    col_style: 'col-6',
    default_value_type: 'CONST',
    // default_value: formatDate(new Date(), 'dd.MM.yyyy', 'en'),
  },
  {
    token: 'endDate',
    name: 'Срок действия (по дату)',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 4,
    col_style: 'col-6',
  },
  {
    token: 'employeeId',
    name: 'Сотрудник',
    attribute_code: 'FIO',
    displayTypeCode: 'DQ',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 2,
    dict_code: 'OS_EMPLOYEES',
    dict_code_property: 'employee_id',
    dict_name_property: 'full_name',
  },
  {
    token: 'organizationId',
    name: 'Организация по умолчанию',
    attribute_code: 'FIO',
    displayTypeCode: 'FB',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 2,
    dict_form_class_ref_name: 'getOrg',
    dict_code_property: 'key',
    dict_name_property: 'label',
  },
  {
    token: 'isActiveFlagCode',
    name: 'Активен?',
    displayTypeCode: 'CH',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    default_value_type: 'CONST',
    default_value: 'N',
  },
];

export const fildListAddNewEdit = [
  {
    token: 'firstLastName',
    name: 'Фамилия, Имя, Отчество',
    displayTypeCode: 'F',
    attribute_code: 'FIO',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 256,
    // value: 'Иванов Иван Иванович',
  },
  {
    token: 'login',
    name: 'Логин',
    displayTypeCode: 'F',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 256,
  },
  {
    token: 'password',
    name: 'Пароль',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 16,
    col_style: 'col-6',
    is_password: true,
  },
  {
    token: 'changePasswordFlagCode',
    name: 'Сменить пароль?',
    displayTypeCode: 'CH',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
  },
  {
    token: 'addInfo',
    name: 'Описание',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 1024,
  },
  {
    token: 'emailAddress',
    name: 'E-Mail',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 128,
  },
  {
    token: 'address',
    name: 'Адрес',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 256,
  },
  {
    token: 'telefon',
    name: 'Телефон',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 80,
    col_style: 'col-6',
  },
  {
    token: 'fax',
    name: 'Факс',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    maxlength: 80,
    col_style: 'col-6',
  },
  {
    token: 'startDate',
    name: 'Срок действия (с даты)',
    attribute_code: 'FIO',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 4,
    col_style: 'col-6',
    default_value_type: 'CONST',
    // default_value: formatDate(new Date(), 'dd.MM.yyyy', 'en'),
  },
  {
    token: 'endDate',
    name: 'Срок действия (по дату)',
    displayTypeCode: 'F',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 4,
    col_style: 'col-6',
  },
  {
    token: 'employeeId',
    name: 'Сотрудник',
    attribute_code: 'FIO',
    displayTypeCode: 'DQ',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 2,
    dict_code: 'OS_EMPLOYEES',
    dict_code_property: 'employee_id',
    dict_name_property: 'full_name',
  },
  {
    token: 'organizationId',
    name: 'Организация по умолчанию',
    attribute_code: 'FIO',
    displayTypeCode: 'FB',
    isNullableFlag: 'N',
    is_editable_flag: 'Y',
    dataTypeId: 2,
    dict_form_class_ref_name: 'getOrg',
    dict_code_property: 'key',
    dict_name_property: 'label',
  },
  {
    token: 'isActiveFlagCode',
    name: 'Активен?',
    displayTypeCode: 'CH',
    isNullableFlag: 'Y',
    is_editable_flag: 'Y',
    dataTypeId: 1,
    default_value_type: 'CONST',
    default_value: 'N',
  },
];

const values = {
  isActiveFlagCode: 'Y',
  address: null,
  changePasswordFlagCode: 'N',
  endDate: null,
  employeeIdName: 'EMP3',
  employeeId: 3,
  addInfo: null,
  login: 'ADMIN',
  userId: 1,
  organizationIdName: 'Головная организация',
  organizationId: 1,
  firstLastName: 'Системный администратор',
  emailAddress: null,
  telefon: null,
  fax: null,
  startDate: '07.02.2007',
};

const test = [
  {
    fieldName: 'user_role_name',
    applicationCode: 'CORE',
    name: 'Наименование пользовательской роли',
    width: 300,
    displayOrder: 1,
    dataTypeId: 1,
    colTypeCode: 'STANDARD',
    sortColName: 'e.name1',
    isSortableFlagCode: 'Y',
    filterCondition: 'LIKE',
    filterColName: 'e.name1',
    filterUpperSign: 'BOTH',
    filterLikePercSign: 'ALL',
    filterGroup: null,
    filterDisplayTypeCode: 'F',
    filterAttributeCode: 'F_STR',
    filterDictCode: null,
    filterCodeProperty: null,
    filterNameProperty: null,
    filterDictFormClassRefName: null,
  },
  {
    fieldName: 'application_name',
    applicationCode: 'CORE',
    name: 'Приложение',
    width: 250,
    displayOrder: 2,
    dataTypeId: 1,
    colTypeCode: 'STANDARD',
    sortColName: 'a.name1',
    isSortableFlagCode: 'Y',
    filterCondition: '=',
    filterColName: 'a.applicationCode',
    filterUpperSign: null,
    filterLikePercSign: null,
    filterGroup: null,
    filterDisplayTypeCode: 'L',
    filterAttributeCode: 'CORE_APPLICATIONS',
    filterDictCode: null,
    filterCodeProperty: 'code',
    filterNameProperty: 'name',
    filterDictFormClassRefName: null,
  },
  {
    fieldName: 'role_name',
    applicationCode: 'CORE',
    name: 'Наименование роли',
    width: 250,
    displayOrder: 3,
    dataTypeId: 1,
    colTypeCode: 'STANDARD',
    sortColName: 'r.name1',
    isSortableFlagCode: 'Y',
    filterCondition: 'LIKE',
    filterColName: 'r.name1',
    filterUpperSign: 'BOTH',
    filterLikePercSign: 'ALL',
    filterGroup: null,
    filterDisplayTypeCode: 'F',
    filterAttributeCode: 'F_STR',
    filterDictCode: null,
    filterCodeProperty: null,
    filterNameProperty: null,
    filterDictFormClassRefName: null,
  },
];

// const filterBlock1 = [
//  {
//     fieldName: 'org_name',
//     name: 'e.organizationId',
//     displayOrder: 2,
//     filterCondition: '=',
//     filterDisplayTypeCode: 'FB',
//     filterDictCode: 'TEST',
//     filterCodeProperty: '-1',
//     width: '220',
//     isSortableFlagCode: 'Y',
//     dataTypeId: 2,

//     applicationCode: 'CORE',
//     colTypeCode: 'STANDARD',
//     sortColName: 'a.name1',
//     filterColName: 'a.applicationCode',
//     filterUpperSign: null,
//     filterLikePercSign: null,
//     filterGroup: null,
//     filterAttributeCode: null,
//     filterNameProperty: 'name',
//     filterDictFormClassRefName: null,
//   },
//     {
//     fieldName: 'user_id',
//     name: 'user_id',
//     displayOrder: 2,
//     filterCondition: 'BETWEEN',
//     filterDisplayTypeCode: 'F',
//     filterDictCode: 'TEST',
//     filterCodeProperty: '-1',
//     width: '220',
//     isSortableFlagCode: 'Y',
//     dataTypeId: 2,

//     applicationCode: 'CORE',
//     colTypeCode: 'STANDARD',
//     sortColName: 'a.name1',
//     filterColName: 'a.applicationCode',
//     filterUpperSign: null,
//     filterLikePercSign: null,
//     filterGroup: null,
//     filterAttributeCode: null,
//     filterNameProperty: 'name',
//     filterDictFormClassRefName: null,
//   },

//     {
//     fieldName: 'first_last_name',
//     name: 'e.firstLastName',
//     displayOrder: 1,
//     filterCondition: 'LIKE',
//     filterDisplayTypeCode: 'F',
//     filterDictCode: 'TEST',
//     filterCodeProperty: '-1',
//     filterUpperSign: 'BOTH',
//     filterLikePercSign: 'ALL',
//     width: '220',
//     isSortableFlagCode: 'Y',
//     dataTypeId: 1,

//     applicationCode: 'CORE',
//     colTypeCode: 'STANDARD',
//     sortColName: 'a.name1',
//     filterColName: 'a.applicationCode',
//     filterGroup: null,
//     filterAttributeCode: null,
//     filterNameProperty: 'name',
//     filterDictFormClassRefName: null,
//   },

//    {
//     fieldName: 'login',
//     name: 'e.login',
//     displayOrder: 1,
//     filterCondition: 'LIKE',
//     filterDisplayTypeCode: 'F',
//     filterDictCode: 'TEST',
//     filterCodeProperty: '-1',
//     filterUpperSign: 'BOTH',
//     filterLikePercSign: 'ALL',
//     width: '140',
//     isSortableFlagCode: 'Y',
//     dataTypeId: 1,

//     applicationCode: 'CORE',
//     colTypeCode: 'STANDARD',
//     sortColName: 'a.name1',
//     filterColName: 'a.applicationCode',
//     filterGroup: null,
//     filterAttributeCode: null,
//     filterNameProperty: 'name',
//     filterDictFormClassRefName: null,
//   },
//   {
//     fieldName: 'is_active_flag_name',
//     name: 'e.isActiveFlagCode',
//     displayOrder: 1,
//     filterCondition: '=',
//     filterDisplayTypeCode: 'L',
//     filterDictCode: 'TEST',
//     filterCodeProperty: '-1',
//     filterUpperSign: 'BOTH',
//     filterLikePercSign: 'ALL',
//       filterAttributeCode: 'YES_NO',
//     width: '70',
//     isSortableFlagCode: 'Y',

//     applicationCode: 'CORE',
//     dataTypeId: 1,
//     colTypeCode: 'STANDARD',
//     sortColName: 'a.name1',
//     filterColName: 'a.applicationCode',
//     filterGroup: null,
//     filterNameProperty: 'name',
//     filterDictFormClassRefName: null,
//   },
// ]
