export const filterBlock = [
  {
    itemName: 'org_name',
    colName: 'e.organizationId',
    dataType: 2,
    condition: '=',
    value: '',
    displayType: 'FB',
    dictCode: 'TEST',
    codeProperty: '-1',
  },
  {
    itemName: 'user_id',
    colName: 'user_id',
    dataType: 2,
    condition: 'BETWEEN',
    value: '',
    displayType: 'F',
  },
  {
    itemName: 'first_last_name',
    colName: 'e.firstLastName',
    dataType: 1,
    condition: 'LIKE',
    upperSign: 'BOTH',
    likePercSign: 'ALL',
    value: '',
    displayType: 'F',
  },
  {
    itemName: 'login',
    colName: 'e.login',
    dataType: 1,
    condition: 'LIKE',
    upperSign: 'BOTH',
    likePercSign: 'ALL',
    value: '',
    displayType: 'F',
  },
  {
    itemName: 'is_active_flag_name',
    colName: 'e.isActiveFlagCode',
    condition: '=',
    dataType: 1,
    displayType: 'L',
    dictCode: 'TEST',
    codeProperty: 'code',
    nameProperty: 'name',
    attrCode: 'YES_NO',
  },
];
